// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TQVaultAE.Persistence;

#nullable disable

namespace TQVaultAE.Persistence.Migrations.Application
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260918221606_ChangeSystemToAvaloniaTypes")]
    partial class ChangeSystemToAvaloniaTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("TQVaultAE.Model.ApplicationInformation", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasJsonPropertyName("name");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("version")
                        .HasJsonPropertyName("version");

                    b.HasKey("Name");

                    b.ToTable("application", (string)null);
                });

            modelBuilder.Entity("TQVaultAE.Model.Settings.Settings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Cheats", "TQVaultAE.Model.Settings.Settings.Cheats#CheatSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("AreCharacterEditingFeaturesEnabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("cheats_character_editing")
                                .HasJsonPropertyName("characterEditingFeatures");

                            b1.Property<bool>("AreCheatsEnabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("cheats_enable")
                                .HasJsonPropertyName("areCheatsEnabled");

                            b1.Property<bool>("AreEpicAndLegendaryAffixesEnabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("cheats_epic_legendary_affixes")
                                .HasJsonPropertyName("epicAndLegendaryAffixes");

                            b1.Property<bool>("AreItemEditingFeaturesEnabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("cheats_item_editing")
                                .HasJsonPropertyName("itemEditingFeatures");

                            b1.Property<bool>("IsItemCopyingEnabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("cheats_item_copying")
                                .HasJsonPropertyName("itemCopying");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Game", "TQVaultAE.Model.Settings.Settings.Game#GameSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("AreCustomMapsEnabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("custom_maps")
                                .HasJsonPropertyName("customMaps");

                            b1.Property<bool>("IsOriginalTqSupportEnabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("original_tq_support")
                                .HasJsonPropertyName("originalTqSupport");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "GamePaths", "TQVaultAE.Model.Settings.Settings.Game#GameSettings.GamePaths#GamePathsSettings", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("ImmortalThroneGamePath")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("paths_immortal_thronw")
                                        .HasJsonPropertyName("ImmortalThroneGamePath");

                                    b2.Property<bool>("IsAutoDetectionEnabled")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("paths_auto_detection")
                                        .HasJsonPropertyName("autoDetect");

                                    b2.Property<string>("TitanQuestGamePath")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("paths_titan_quest")
                                        .HasJsonPropertyName("TitanQuestGamePath");
                                });
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "General", "TQVaultAE.Model.Settings.Settings.General#GeneralSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("IsAutoStackingEnabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("auto_stacking")
                                .HasJsonPropertyName("autoStacking");

                            b1.Property<bool>("IsBypassConfirmationMessagesEnabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("bypass_confirmation_messages")
                                .HasJsonPropertyName("bypassConfirmationMessages");

                            b1.Property<bool>("IsBypassTitleScreenEnabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("bypass_title_screen")
                                .HasJsonPropertyName("bypassTitleScreenAutomatically");

                            b1.Property<bool>("IsDetailedTooltipViewEnabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("detailed_tooltip_view")
                                .HasJsonPropertyName("detailedTooltipView");

                            b1.Property<bool>("IsHotReloadEnabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("hot_reload")
                                .HasJsonPropertyName("hotReload");

                            b1.Property<bool>("IsLoadAllVaultAndCharacterDataOnStartupEnabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("load_all_vault_and_character_data_on_startup")
                                .HasJsonPropertyName("loadAllVaultAndCharacterFilesOnStartup");

                            b1.Property<bool>("IsLoadLastOpenedCharacterAutomaticallyEnabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("load_last_opened_character")
                                .HasJsonPropertyName("loadLastOpenedCharacterAutomatically");

                            b1.Property<bool>("IsLoadLastOpenedVaultAutomaticallyEnabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("load_last_opened_vault")
                                .HasJsonPropertyName("loadLastOpenedVaultAutomatically");

                            b1.Property<bool>("IsPlayerEquipmentReadOnlyEnabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("player_equipment_read_only")
                                .HasJsonPropertyName("playerEquipmentReadOnly");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "BackupSettings", "TQVaultAE.Model.Settings.Settings.General#GeneralSettings.BackupSettings#BackupSettings", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<bool>("ArePlayerSavesEnabled")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("backup_player_saves")
                                        .HasJsonPropertyName("backupPlayerSaves");

                                    b2.Property<string>("GitRepositoryUrl")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("backup_repository_url")
                                        .HasJsonPropertyName("gitRepositoryUrl");

                                    b2.Property<bool>("IsBackupEnabled")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("backup")
                                        .HasJsonPropertyName("backup");
                                });
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "UserInterface", "TQVaultAE.Model.Settings.Settings.UserInterface#UserInterfaceSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("AreSoundsEnabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("play_sounds")
                                .HasJsonPropertyName("sounds");

                            b1.Property<string>("Font")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("font")
                                .HasJsonPropertyName("font");

                            b1.Property<bool>("IsItemRequirementRestrictionEnabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("item_requirements_restriction")
                                .HasJsonPropertyName("itemRequirementRestriction");

                            b1.Property<double>("ItemBackgroundTransparencyLevel")
                                .HasColumnType("REAL")
                                .HasColumnName("item_background_transparency_level")
                                .HasJsonPropertyName("itemBackgroundTransparencyLevel");

                            b1.Property<int>("Language")
                                .HasColumnType("INTEGER")
                                .HasColumnName("language")
                                .HasJsonPropertyName("language");
                        });

                    b.HasKey("Id");

                    b.ToTable("settings", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "settings");
                });

            modelBuilder.Entity("TQVaultAE.Model.UI.Icon", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ResourcePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("resource_path");

                    b.HasKey("Id");

                    b.ToTable("icons", (string)null);
                });

            modelBuilder.Entity("TQVaultAE.Model.UI.IconSet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("IconDownId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("icon_down");

                    b.Property<string>("IconHoverId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("icon_hover");

                    b.Property<string>("IconUpId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("icon_up");

                    b.HasKey("Id");

                    b.HasIndex("IconDownId");

                    b.HasIndex("IconHoverId");

                    b.HasIndex("IconUpId");

                    b.ToTable("icon_sets", (string)null);
                });

            modelBuilder.Entity("TQVaultAE.Model.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasJsonPropertyName("name");

                    b.Property<Guid>("SettingsId")
                        .HasColumnType("TEXT")
                        .HasColumnName("settings_id");

                    b.HasKey("Id");

                    b.HasIndex("SettingsId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TQVaultAE.Model.UI.IconSet", b =>
                {
                    b.HasOne("TQVaultAE.Model.UI.Icon", "IconDown")
                        .WithMany()
                        .HasForeignKey("IconDownId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TQVaultAE.Model.UI.Icon", "IconHover")
                        .WithMany()
                        .HasForeignKey("IconHoverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TQVaultAE.Model.UI.Icon", "IconUp")
                        .WithMany()
                        .HasForeignKey("IconUpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IconDown");

                    b.Navigation("IconHover");

                    b.Navigation("IconUp");
                });

            modelBuilder.Entity("TQVaultAE.Model.User", b =>
                {
                    b.HasOne("TQVaultAE.Model.Settings.Settings", "Settings")
                        .WithMany()
                        .HasForeignKey("SettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
