// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TQVaultAE.Persistence;

#nullable disable

namespace TQVaultAE.Persistence.Migrations.Data
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20260917110454_TempRemoveIconFromVaultTab")]
    partial class TempRemoveIconFromVaultTab
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("TQVaultAE.Model.Items.Affix", b =>
                {
                    b.Property<string>("Path")
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.HasKey("Path");

                    b.ToTable("affix", (string)null);
                });

            modelBuilder.Entity("TQVaultAE.Model.Items.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanStack")
                        .HasColumnType("INTEGER")
                        .HasColumnName("can_stack");

                    b.Property<int>("Class")
                        .HasColumnType("INTEGER")
                        .HasColumnName("class");

                    b.Property<int>("Classification")
                        .HasColumnType("INTEGER")
                        .HasColumnName("classification");

                    b.Property<int>("Cost")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cost");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER")
                        .HasColumnName("level");

                    b.Property<int>("MaxTransparency")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_transparency");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("position");

                    b.Property<string>("PrefixId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("prefix");

                    b.Property<string>("ResourcePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("resource_path");

                    b.Property<float>("Scale")
                        .HasColumnType("REAL")
                        .HasColumnName("scale");

                    b.Property<int>("Seed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("seed");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("size");

                    b.Property<int>("StackCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stack_count");

                    b.Property<string>("SuffixId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("suffix");

                    b.Property<Guid>("TalismanOneId")
                        .HasColumnType("TEXT")
                        .HasColumnName("talisman_one");

                    b.Property<Guid>("TalismanTwoId")
                        .HasColumnType("TEXT")
                        .HasColumnName("talisman_two");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("template_name");

                    b.Property<int>("Var1")
                        .HasColumnType("INTEGER")
                        .HasColumnName("var1");

                    b.Property<int>("Var2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("var2");

                    b.HasKey("Id");

                    b.HasIndex("PrefixId");

                    b.HasIndex("SuffixId");

                    b.HasIndex("TalismanOneId");

                    b.HasIndex("TalismanTwoId");

                    b.ToTable("items", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("Item");

                    b
                        .UseTphMappingStrategy()
                        .HasAnnotation("Relational:JsonPropertyName", "items");
                });

            modelBuilder.Entity("TQVaultAE.Model.UI.Icon", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Icon");
                });

            modelBuilder.Entity("TQVaultAE.Model.UI.IconSet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("IconDownId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconHoverId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUpId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IconDownId");

                    b.HasIndex("IconHoverId");

                    b.HasIndex("IconUpId");

                    b.ToTable("icon_sets", (string)null);
                });

            modelBuilder.Entity("TQVaultAE.Model.Vaults.Vault", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasJsonPropertyName("name");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type")
                        .HasJsonPropertyName("type");

                    b.HasKey("Id");

                    b.ToTable("vaults", (string)null);
                });

            modelBuilder.Entity("TQVaultAE.Model.Vaults.VaultTab", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    b.Property<string>("IconId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("iconId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasJsonPropertyName("name");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("TEXT")
                        .HasColumnName("vault_id")
                        .HasJsonPropertyName("vault");

                    b.Property<Guid?>("VaultId1")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VaultId");

                    b.HasIndex("VaultId1");

                    b.ToTable("vault_tabs", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "tabs");
                });

            modelBuilder.Entity("TQVaultAE.Persistence.Data.Entities.ItemToVaultTab", b =>
                {
                    b.Property<Guid>("VaultTabId")
                        .HasColumnType("TEXT")
                        .HasColumnName("vault_tab_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("item_id");

                    b.HasKey("VaultTabId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("vault_tab_item", (string)null);
                });

            modelBuilder.Entity("TQVaultAE.Model.Items.TalismanItem", b =>
                {
                    b.HasBaseType("TQVaultAE.Model.Items.Item");

                    b.Property<string>("Bonus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TalismanType")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("TalismanItem");
                });

            modelBuilder.Entity("TQVaultAE.Model.Items.Item", b =>
                {
                    b.HasOne("TQVaultAE.Model.Items.Affix", "Prefix")
                        .WithMany()
                        .HasForeignKey("PrefixId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TQVaultAE.Model.Items.Affix", "Suffix")
                        .WithMany()
                        .HasForeignKey("SuffixId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TQVaultAE.Model.Items.TalismanItem", "TalismanOne")
                        .WithMany()
                        .HasForeignKey("TalismanOneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TQVaultAE.Model.Items.TalismanItem", "TalismanTwo")
                        .WithMany()
                        .HasForeignKey("TalismanTwoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Prefix");

                    b.Navigation("Suffix");

                    b.Navigation("TalismanOne");

                    b.Navigation("TalismanTwo");
                });

            modelBuilder.Entity("TQVaultAE.Model.UI.IconSet", b =>
                {
                    b.HasOne("TQVaultAE.Model.UI.Icon", "IconDown")
                        .WithMany()
                        .HasForeignKey("IconDownId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TQVaultAE.Model.UI.Icon", "IconHover")
                        .WithMany()
                        .HasForeignKey("IconHoverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TQVaultAE.Model.UI.Icon", "IconUp")
                        .WithMany()
                        .HasForeignKey("IconUpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IconDown");

                    b.Navigation("IconHover");

                    b.Navigation("IconUp");
                });

            modelBuilder.Entity("TQVaultAE.Model.Vaults.VaultTab", b =>
                {
                    b.HasOne("TQVaultAE.Model.Vaults.Vault", "Vault")
                        .WithMany()
                        .HasForeignKey("VaultId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TQVaultAE.Model.Vaults.Vault", null)
                        .WithMany("Tabs")
                        .HasForeignKey("VaultId1");

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("TQVaultAE.Persistence.Data.Entities.ItemToVaultTab", b =>
                {
                    b.HasOne("TQVaultAE.Model.Items.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TQVaultAE.Model.Vaults.VaultTab", "VaultTab")
                        .WithMany()
                        .HasForeignKey("VaultTabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("VaultTab");
                });

            modelBuilder.Entity("TQVaultAE.Model.Vaults.Vault", b =>
                {
                    b.Navigation("Tabs");
                });
#pragma warning restore 612, 618
        }
    }
}
